[package]
name = "egui_wasm_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
eframe = "0.18.0"
egui = "0.18.1"
rfd = "0.8.2"
tempfile = "3.3.0"
